In [1]:
import numpy as np

In [3]:
a=np.array([[22,44,24,24],[22,45,77]])
print(np.append(a,55))
print(np.append(a,[22,44]))

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [5]:
a=np.array([[22,44,24,24],[22,45,77,33]])
print(a)

[[22 44 24 24]
 [22 45 77 33]]


In [6]:
print(np.append(a,[22,44]))

[22 44 24 24 22 45 77 33 22 44]


In [7]:
print(np.append(a,[22,44],axis=1))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [11]:
a=np.array([[22,44,24,24],[22,45,77,33]])

In [13]:
print(np.append(a,[22,44],axis=1))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [14]:
a=np.array([22,55,35,88,44])
print(np.insert(a,2,777))

[ 22  55 777  35  88  44]


In [15]:
a=np.array([[22,44,24,24],[22,45,77,33]])
print(np.insert(a,1,[23,55],axis=1))

[[22 23 44 24 24]
 [22 55 45 77 33]]


In [17]:
print(np.insert(a,0,[23,55],axis=0))

ValueError: could not broadcast input array from shape (1,2) into shape (1,4)

In [18]:
print(np.insert(a,2,[22,54],axis=0))

ValueError: could not broadcast input array from shape (1,2) into shape (1,4)

In [19]:
pirnt(a)

NameError: name 'pirnt' is not defined

In [20]:
print(a)

[[22 44 24 24]
 [22 45 77 33]]


In [21]:
x=np.array(22,44,3,66,33,77,44)

TypeError: array() takes from 1 to 2 positional arguments but 7 were given

In [22]:
x=np.array([22,44,33,66,88,66])

In [23]:
print(x)

[22 44 33 66 88 66]


In [24]:
print(np.delete(x,0))

[44 33 66 88 66]


In [25]:
print(np.delete(x,3))

[22 44 33 88 66]


In [26]:
print(np.delete(a,1))

[22 24 24 22 45 77 33]


In [27]:
print(np.delete(x,1))

[22 33 66 88 66]


In [28]:
print(np.sort(x))

[22 33 44 66 66 88]


In [30]:
s=np.where(x%2==0)
print(s)

(array([0, 1, 3, 4, 5], dtype=int64),)


In [36]:
s=np.array([22,44,35,33,77,44])
fa=s%2==1
new=s[fa]
print(new)

[35 33 77]
