In [29]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statistics as stats

In [2]:
a=np.array([2,3,4,5,6,5])
b=np.array([3,54,5,4,3,3])
print(a)

[2 3 4 5 6 5]


In [3]:
print(a),print(b)

[2 3 4 5 6 5]
[ 3 54  5  4  3  3]


(None, None)

In [4]:
print(a+b)

[ 5 57  9  9  9  8]


In [5]:
np.sum(a),np.sum(b)

(25, 72)

In [6]:
data=np.array([[2,3,4,3,2],[4,6,4,3,4]])
np.sum(data)

35

In [7]:
data.describe()

AttributeError: 'numpy.ndarray' object has no attribute 'describe'

In [ ]:
print("data shape is=",np.shape(data))

In [ ]:
print("data size is=",np.size(data))

In [ ]:
print("data dimension is=",np.ndim(data))

In [ ]:
np.size(a)

In [ ]:
print(data.dtype)

In [ ]:
data.astype(float)

In [ ]:
print(data.dtype)

In [ ]:
data

In [ ]:
data2=data.copy()

In [ ]:
data2

In [ ]:
np.sum(data)

In [ ]:
np.subtract(a,b)

In [ ]:
np.add(a,b)

In [ ]:
a,b

In [ ]:
np.round(np.divide(a,b))

In [ ]:
np.sqrt(a)

In [ ]:
np.power(a,2)

In [ ]:
np.exp(a)

In [ ]:
a

In [8]:
print(np.concatenate([a,b]))

[ 2  3  4  5  6  5  3 54  5  4  3  3]


In [9]:
print(np.concatenate([a,b],axis=2))

AxisError: axis 2 is out of bounds for array of dimension 1

In [10]:
print(np.hstack([a,b]))

[ 2  3  4  5  6  5  3 54  5  4  3  3]


In [11]:
np.insert(a,1,444)

array([  2, 444,   3,   4,   5,   6,   5])

In [12]:
np.insert(a,6,4232)

array([   2,    3,    4,    5,    6,    5, 4232])

In [13]:
np.delete(a,[5])

array([2, 3, 4, 5, 6])

In [14]:
sortdata=np.array([3,4,2,5,2,2,55,22,55,22,5,21,3])
print(np.sort(sortdata))

[ 2  2  2  3  3  4  5  5 21 22 22 55 55]


In [15]:
s=np.where(sortdata==2)

In [16]:
print(s)

(array([2, 4, 5], dtype=int64),)


In [17]:
arr=np.array([3,22,44,22,44,66,35,87])
arr

array([ 3, 22, 44, 22, 44, 66, 35, 87])

In [18]:
fa=arr>32
print(fa)

[False False  True False  True  True  True  True]


In [21]:
np.cumprod(arr)

array([          3,          66,        2904,       63888,     2811072,
         185530752, -2096358272, -1994543232])

In [22]:
np.cumsum(arr)

array([  3,  25,  69,  91, 135, 201, 236, 323])

In [34]:
datalist=np.array([2,3,2,4,2,4,2,4])
np.mean(datalist),np.sort(datalist),np.median(datalist),stats.mode(datalist)

(2.875, array([2, 2, 2, 2, 3, 4, 4, 4]), 2.5, 2)

In [33]:
stats.mode(datalist)

2

In [35]:
np.corrcoef([a,b])

array([[ 1.       , -0.3893167],
       [-0.3893167,  1.       ]])