In [1]:
import numpy as np

In [6]:
a=np.array([12,33,22])
b=np.array([33,3,34,])
c=a+b
d=a-b
e=a*b
f=a/b
print(c)
print(d)
print(e)
print(f)
print(arr[1:2])

[45 36 56]
[-21  30 -12]
[396  99 748]
[ 0.36363636 11.          0.64705882]


NameError: name 'arr' is not defined

In [7]:
r=np.array([
    [22,33,22,33],[22,11,22,33],[22,33,22,11],[22,11,22,11]
])
print(r)

[[22 33 22 33]
 [22 11 22 33]
 [22 33 22 11]
 [22 11 22 11]]


In [8]:
print(r[1:2])

[[22 11 22 33]]


In [9]:
print(r[1,3])

33


In [12]:
print(r[1,0:3])

[22 11 22]


In [13]:
print(np.shape(r))

(4, 4)


In [14]:
print(np.size(r))

16


In [15]:
print(np.ndim(r))

2


In [16]:
print(r.dtype)

int32


In [17]:
print(len(r))


4


In [18]:
r.astype(float)

array([[22., 33., 22., 33.],
       [22., 11., 22., 33.],
       [22., 33., 22., 11.],
       [22., 11., 22., 11.]])

In [19]:
r.astype(int)

array([[22, 33, 22, 33],
       [22, 11, 22, 33],
       [22, 33, 22, 11],
       [22, 11, 22, 11]])

In [20]:
print(a+b)

[45 36 56]


In [21]:
s=np.array([4,5,6,7])
p=np.array([3])
print(np.power(s,p))

[ 64 125 216 343]


In [26]:
x=np.array([16,25,36,49])
y=x.astype(int)
print(np.sqrt(y))

[4. 5. 6. 7.]
